<?php
/**
 * Plugin Name: T-Shirt Designer
 * Plugin URI: http://www.tsirtdesinger.com
 * Description: This plugin will let you create a t-shirt design in your own. This plugin will let you create a t-shirt design in your own. This plugin will let you create a t-shirt design in your own. This plugin will let you create a t-shirt design in your own.
 * Author URI: http://www.jesuserwinsuarez.com
 * Author: Jesus Erwin Suarez
 * License: GPLv2
 * Version: 1.0
 */

require("autoload.php");

add_action("admin_menu", "tsd_admin_menu");
function tsd_admin_menu() {
    add_menu_page('T-Shirt Designer', 'T Shirt Designer', 'manage_options', "t-shirt-designer", 'tsd_admin_general');
    add_submenu_page('t-shirt-designer', 'settings', 'settings', 'manage_options', 't-shirt-designer-settings', 'tsd_admin_settings');
    add_submenu_page('t-shirt-designer', 'upload', 'upload', 'manage_options', 't-shirt-designer-upload', 'tsd_admin_upload');
}
function tsd_admin_settings() {
    ?>
        <h1> This is the settings</h1>
    <?php
}
function tsd_admin_general(){
    ?>
    <h1> This is the general settings </h1>
<?php
}
?>





<?php 




function getPathToFile($filePath) {
 
	$filePath = str_replace('http://dev.app.thesmsfacademy.com.au/', '', $filePath);
	$filePath = str_replace('https://app.thesmsfacademy.com.au/', '', $filePath); 
	return ABSPATH . $filePath;
}
// You codes

function my_cust_filename($dir, $name, $ext) {
    return $_SESSION['name'] . "updatename" . $name.$ext;
}
 


function tsd_admin_upload(){   ?>
	

	<form action="<?php echo $_SERVER['PHP_SELF']; ?>?page=t-shirt-designer-upload" method="post" enctype="multipart/form-data">
	    Select image to upload:
	    <input type="file" name="file" id="fileToUpload">
	    <input type="submit" value="Upload Image" name="submit">
	</form> 
	<pre>


	<?php 	


	if(isset($_FILES['file'])){
		echo "<br>file has content";
	} else {
		echo "<br>file has no content";
	}


	$filePath =  ABSPATH . 'wp-content/uploads/2016/06/2.jpg';
	$fileName = '2.jpg'; 


	// $filePath = 'http://localhost/Tim/app.thesmsfacademy.com.au/developer/wordpress/wp-content/uploads/2016/06/2-1.jpg';


	//  unlink($filePath);


http://dev.app.thesmsfacademy.com.au/wp-content/uploads\templatemerge\masters/2016/06/Doc1.docx


echo " file path: " . getPathToFile('http://dev.app.thesmsfacademy.com.au/wp-content/uploads\templatemerge\masters/2016/06/Doc1.docx');




echo " <br>$filePath  ";

	if(isset($_POST['submit'])) {


		if ( ! function_exists( 'wp_handle_upload' ) ) {
		    require_once( ABSPATH . 'wp-admin/includes/file.php' );
		}

		$uploadedfile = $_FILES['file'];


		$_SESSION['name'] = 'newsessionanme';


		print_r($uploadedfile);

	   $filePath = ABSPATH . '/wp-content/uploads/2016/06/' .$uploadedfile['name']; 
		unlink($filePath);



		echo "<br> file name uploaded: " . $uploadedfile['name'] . '<br>';

 		 
		$upload_overrides = array( 'test_form' => false,'unique_filename_callback' => 'my_cust_filename' );

	


		$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );




		if ( $movefile && ! isset( $movefile['error'] ) ) {
		    echo "File is valid, and was successfully uploaded.\n";
		    var_dump( $movefile );

		    print_r($movefile);
		} else {
		    /**
		     * Error generated by _wp_handle_upload()
		     * @see _wp_handle_upload() in wp-admin/includes/file.php
		     */
		    echo $movefile['error'];
		}



		$movefileArray = explode('/', $movefile['file']); 

		print_r($movefileArray); 

		
		$fileName = $movefileArray[count($movefileArray)-1]; 


		echo "file name inserted : " . $fileName . '<br>';



		echo "<br> Hit upload ";



	} else {
		echo "<br>Not hit upload";
	}


	?>


<?php } ?>



